Controllers/PostAdminController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Dev_Blog.Data;
using Dev_Blog.Models;
using Dev_Blog.Utils;
using Dev_Blog.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace Dev_Blog.Controllers
{
    [Authorize(Roles = "Admin, Author")]
    public class PostAdminController : Controller
    {
        private readonly ILogger<PostAdminController> logger;
        private readonly BlogDBContext context;
        private readonly IWebHostEnvironment env;

        public PostAdminController(ILogger<PostAdminController> logger, IWebHostEnvironment env, BlogDBContext context)
        {
            this.logger = logger;
            this.context = context;
            this.env = env;
        }

        // GET: PostAdmin
        [HttpGet]
        public async Task<ActionResult> Index(int? currPage)
        {
            logger.LogTrace("GET: PostAdmin, Index, currPage = {currPage}", currPage);
            const int postsPerPage = 30;

            IQueryable<Post> posts = context.Posts.OrderByDescending(p => p.DateCreated);

            if (!User.IsInRole("Admin"))
            {
                posts = posts.Where(p => p.Author.UserName == User.Identity.Name && p.DateDeleted == null);
            }

            if (currPage == null || currPage < 1)
            {
                currPage = 1;
            }

            PaginatedData<Post> result = new PaginatedData<Post>()
            {
                PageSize = postsPerPage,
                CurrentPage = currPage.Value,
                Count = await posts.CountAsync()
            };

            result.Data = posts.Skip((currPage.Value - 1) * postsPerPage).Take(postsPerPage);
            return View(result);
        }

        // GET: PostAdmin/Details/5
        [HttpGet]
        public ActionResult Details(long id)
        {
            logger.LogTrace("GET: PostAdmin, Details, id = {id}", id);
            Post post = getAllowedPost(id);

            if (post == null)
            {
                return postNotFound(id);
            }

            return View(post);
        }

        // GET: PostAdmin/Create
        [HttpGet]
        public ActionResult Create()
        {
            logger.LogTrace("GET: PostAdmin, Create");
            PostViewModel viewModel = new PostViewModel();
            return View(viewModel);
        }

        // POST: PostAdmin/Create
        [HttpPost]
        [RequestSizeLimit(Int32.MaxValue)]
        public ActionResult Create(PostViewModel viewModel)
        {
            logger.LogTrace("POST: PostAdmin, Create");
            validatePost(viewModel);

            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            Post post = new Post
            {
                Author = context.Users.Where(a => a.Id == User.FindFirst(ClaimTypes.NameIdentifier).Value).First(),
                Content = viewModel.Content,
                Stub = viewModel.Stub,
                DateDeleted = null,
                DateModified = null,
                DatePublished = null,
                Title = viewModel.Title,
                IsAboutPage = viewModel.IsAboutPage
            };

            post.Tags = Tag.ToPostTags(context, post, viewModel.Tags);
            context.Add(post);
            context.SaveChanges();
            string imagePostDirectory = getImagePostDirectory(post);
            string audioPostDirection = getAudioPostDirectory(post);
            Directory.CreateDirectory(Path.Combine(env.WebRootPath, imagePostDirectory));
            Directory.CreateDirectory(Path.Combine(env.WebRootPath, audioPostDirection));


            if (viewModel.Thumbnail != null)
            {
                setThumbnail(post, viewModel.Thumbnail);
            }
            int refIndex = 1;
            foreach (var file in viewModel.Files)
            {
                addFileAndUpdate(post, file, refIndex);
                refIndex++;
            }

            //Set the publish date to the post's creation date if an older date is specified. Leaves it as null if the post wasn't published yet.
            if (viewModel.Publish)
            {
                if (viewModel.Schedule)
                {
                    //TODO: Create scheduled task for the given date
                    post.DatePublished = viewModel.PublishDate;
                }
                else
                {
                    //TODO: Update subscribers
                    post.DatePublished = post.DateCreated;
                }
            }

            context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        // GET: PostAdmin/Edit/5
        [HttpGet]
        public ActionResult Edit(long id)
        {
            logger.LogTrace("GET: PostAdmin, Edit, id = {id}", id);
            Post post = getAllowedPost(id);

            if (post == null)
            {
                return postNotFound(id);
            }

            var viewModel = new PostViewModel()
            {
                Content = post.Content,
                Publish = post.DatePublished != null,
                Schedule = false,
                IsAboutPage = post.IsAboutPage,
                PublishDate = post.DatePublished < DateTime.Now ? null : post.DatePublished,
                AutoGenerateStub = false,
                Stub = post.Stub,
                Tags = post.Tags.Select(t => t.TagID).ToHashSet(),
                Title = post.Title
            };

            ViewData["FileCount"] = post.Files.Count + 1;

            return View(viewModel);
        }

        // POST: PostAdmin/Edit/5
        [HttpPost]
        [RequestSizeLimit(Int32.MaxValue)]
        public ActionResult Edit(long id, PostViewModel viewModel)
        {
            logger.LogTrace("GET: PostAdmin, Edit, id = {id}", id);
            if (viewModel.ID != id)
            {
                return postNotFound(id);
            }

            Post post = getAllowedPost(id);

            if (post == null)
            {
                return postNotFound(id);
            }

            DateTime now = DateTime.Now;
            try
            {
                validatePost(viewModel);

                if (!ModelState.IsValid)
                {
                    return View(viewModel);
                }

                post.Tags = Tag.ToPostTags(context, post, viewModel.Tags);
                bool isJustPublished = !post.Published && viewModel.Publish;
                if (isJustPublished)
                {
                    post.DateModified = null;
                }
                else
                {
                    post.DateModified = now;
                }

                post.Content = viewModel.Content;
                post.Title = viewModel.Title;
                if (viewModel.Thumbnail != null)
                {
                    setThumbnail(post, viewModel.Thumbnail);
                }

                int refIndex = post.Files.Count + 1;
                foreach (var file in viewModel.Files)
                {
                    addFileAndUpdate(post, file, refIndex);
                    refIndex++;
                }

                if (viewModel.Publish)
                {
                    if (viewModel.Schedule)
                    {
                        //TODO: Create scheduled task for the given date
                        post.DatePublished = viewModel.PublishDate;
                    }
                    else
                    {
                        //TODO: Send email subscribers
                        post.DatePublished ??= now;
                    }
                }
                else
                {
                    post.DatePublished = null;
                }

                post.IsAboutPage = viewModel.IsAboutPage;

                context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(viewModel);
            }
        }

        // GET: PostAdmin/Delete/5
        [HttpGet]
        public ActionResult Delete(long id)
        {
            logger.LogTrace("GET: PostAdmin, Delete, id = {id}", id);
            Post post = getAllowedPost(id);

            if (post == null)
            {
                return postNotFound(id);
            }

            return View(post);
        }

        // POST: PostAdmin/Delete/5
        [HttpPost]
        public ActionResult Delete(long id, Post post)
        {
            logger.LogTrace("POST: PostAdmin, Delete, id = {id}", id);
            if (post.ID != id)
            {
                ModelState.AddModelError("", "Wrong ID");
                return View(post);
            }

            post = getAllowedPost(id);

            if (post == null)
            {
                return postNotFound(id);
            }

            post.DateDeleted = DateTime.Now;
            context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public string PreviewContent(string content)
        {
            return MarkdownParser.ParseString(content);
        }

        /// <summary>
        /// Returns the PostNotFound view with a 404 error code.
        /// </summary>
        /// <param name="id">The id of the post that was tried to be reached</param>
        /// <returns></returns>
        private ActionResult postNotFound(long id)
        {
            Response.StatusCode = 404;
            return View(nameof(postNotFound), id);
        }

        /// <summary>
        /// Returns the specified post if the current user is allowed to access or modify it. Null otherwise
        /// </summary>

Views/PostAdmin/Create.cshtml
@model Dev_Blog.ViewModels.PostViewModel

@{
    ViewData["Title"] = "Create Post";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Create"] = true;
}

<h1>Create a new blog post</h1>

<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Create" asp-controller="PostAdmin" enctype="multipart/form-data">
            <partial name="_PostViewModelEditor" model="Model" />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<button class="btn btn-secondary" id="update-preview">Update preview</button>
<h4>Preview</h4>
<div class="row">
    <div id="post-preview" class="col-md-12 post">@Html.Raw(Dev_Blog.Utils.MarkdownParser.ParseString(Model.Content))</div>
</div>
<hr />
<div>
    <a asp-action="Index">Back to post list</a>
</div>


@section Scripts {
    <script>var startRef = 1;</script>
    <environment include="Development">
        <script src="~/js/postAdmin.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/admin.min.js" asp-append-version="true"></script>
    </environment>
}

Views/PostAdmin/Delete.cshtml
@model Dev_Blog.Models.Post

@{
    ViewData["Title"] = "Delete post";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this post?</h3>
<div>
    <h4>Post</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/PostAdmin/Details.cshtml
@using Dev_Blog.Utils

@model Dev_Blog.Models.Post

@{
    ViewData["Title"] = $"Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Post</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Stub)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Stub)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DatePublished)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DatePublished)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateModified)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateModified)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateDeleted)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateDeleted)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Author.Id)
        </dd>
    </dl>
    <h5>@Html.DisplayNameFor(model => model.Content)</h5>
    <div class="post">
        @Html.Raw(MarkdownParser.ParseString(Model.Content))
    </div>
    <br />
    <h5>Raw</h5>
    <div>
        @foreach (var line in @Model.Content.Split("\n"))
        {
            <p>
                @line
            </p>
        }
    </div>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/PostAdmin/Edit.cshtml
@model Dev_Blog.ViewModels.PostViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Create"] = false;
}

<h1>Edit post</h1>

<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Edit" asp-controller="PostAdmin" enctype="multipart/form-data">
            @Html.HiddenFor(model => model.ID)
            <partial name="_PostViewModelEditor" model="Model" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<button class="btn btn-secondary" id="update-preview">Update preview</button>
<h4>Preview</h4>
<div class="row">
    <div id="post-preview" class="col-md-12">
        @Html.Raw(Dev_Blog.Utils.MarkdownParser.ParseString(Model.Content))
    </div>
</div>
<hr />
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script>var startRef = @ViewData["FileCount"];</script>
    <environment include="Development">
        <script src="~/js/postAdmin.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/admin.min.js" asp-append-version="true"></script>
    </environment>
}

Views/PostAdmin/Index.cshtml
@model Dev_Blog.Utils.PaginatedData<Dev_Blog.Models.Post>

@{
    ViewData["Title"] = "Posts";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Posts</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Data.FirstOrDefault().ThumbnailPath)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Data.FirstOrDefault().Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Data.FirstOrDefault().Stub)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Data.FirstOrDefault().DateCreated)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Data.FirstOrDefault().DatePublished)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Data.FirstOrDefault().DateModified)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Data.FirstOrDefault().DateDeleted)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Data.FirstOrDefault().Views)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Data)
        {

            <tr>
                <td>
                    <img src="@item.ThumbnailPath" alt="@item.Title" title="@item.Title" class="thumbnail" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Stub)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateCreated)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DatePublished)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateModified)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateDeleted)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Views)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@if (Model.TotalPages > 1)
{
    <p>Page @Model.CurrentPage of @Model.TotalPages</p>
    <ul class="pagination">
        <li class="page-item @(Model.CurrentPage == 1 ? "disabled" : "")">
            <a asp-action="Index" asp-route-currPage="1" class="page-link">First</a>
        </li>
        <li class="page-item @(Model.CurrentPage == 1 ? "disabled" : "")">
            <a asp-action="Index" asp-route-currPage="@(Model.CurrentPage - 1)" class="page-link">Previous</a>
        </li>
        <li class="page-item @(Model.CurrentPage == Model.TotalPages ? "disabled" : "")">
            <a asp-action="Index" asp-route-currPage="@(Model.CurrentPage + 1)" class="page-link">Next</a>
        </li>
        <li class="page-item @(Model.CurrentPage == Model.TotalPages ? "disabled" : "")">
            <a asp-action="Index" asp-route-currPage="@Model.TotalPages" class="page-link">Last</a>
        </li>
    </ul>
}

Views/PostAdmin/PostNotFound.cshtml
@model long

@{
    ViewData["Title"] = "Post not found";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Post not found</h1>
<div class="alert alert-danger" role="alert">
    The post with ID @Model was not found.
    <br />
    <a class="alert-link" asp-action="Index">Back to post list</a>
</div>

Views/PostAdmin/_NavPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Dev_Blog.Models

@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

@if (SignInManager.IsSignedIn(User) && (User.IsInRole("Admin") || User.IsInRole("Author")))
{
    <li class="nav-item">
        <a id="manage" class="nav-link" asp-controller="PostAdmin" asp-action="Index" title="Posts">Posts Administration</a>
    </li>
}

Views/PostAdmin/_PostViewModelEditor.cshtml
@model Dev_Blog.ViewModels.PostViewModel

<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<div class="form-group">
    <label asp-for="Title" class="control-label"></label>
    <input asp-for="Title" class="form-control" />
    <span asp-validation-for="Title" class="text-danger"></span>
</div>
@if ((bool)ViewData["Create"])
{
    <div class="form-group form-check">
        <label class="form-check-label">
            <input class="form-check-input" asp-for="AutoGenerateStub" /> @Html.DisplayNameFor(model => model.AutoGenerateStub)
        </label>
    </div>
    <div class="form-group">
        <label asp-for="Stub" class="control-label"></label>

        @if (Model.AutoGenerateStub)
        {
            <input asp-for="Stub" class="form-control stub" readonly />
        }
        else
        {
            <input asp-for="Stub" class="form-control stub" />
        }
        <span asp-validation-for="Stub" class="text-danger"></span>
    </div>
}
else
{
    <div class="form-group form-check" title="Cannot modify the post's stub once created">
        <label class="form-check-label">
            <input class="form-check-input" asp-for="AutoGenerateStub" disabled /> @Html.DisplayNameFor(model => model.AutoGenerateStub)
        </label>
    </div>
    <div class="form-group" title="Cannot modify the post's stub once created">
        <label asp-for="Stub" class="control-label"></label>
        <input asp-for="Stub" class="form-control stub" readonly="@(true)" />
        <span asp-validation-for="Stub" class="text-danger"></span>
    </div>
}
<div class="form-group">
    <label asp-for="Thumbnail" class="control-label"></label>
    <input asp-for="Thumbnail" class="form-control" accept="image/*" />
    <span asp-validation-for="Thumbnail" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Content" class="control-label"></label>
    <textarea asp-for="Content" class="form-control post-content">@Model.Content</textarea>
    <span asp-validation-for="Content" class="text-danger"></span>
</div>
<div class="form-group form-check">
    <label class="form-check-label">
        <input class="form-check-input" asp-for="Publish" /> @Html.DisplayNameFor(model => model.Publish)
    </label>
</div>
<div class="form-group form-check">
    <label class="form-check-label">
        <input class="form-check-input" asp-for="Schedule" /> @Html.DisplayNameFor(model => model.Schedule)
    </label>
</div>
<div class="form-group form-check">
    <label class="form-check-label">
        <input class="form-check-input" asp-for="IsAboutPage" /> @Html.DisplayNameFor(model => model.IsAboutPage)
    </label>
</div>
<div class="form-group">
    <label asp-for="PublishDate" class="control-label"></label>
    <input asp-for="PublishDate" class="form-control" />
    <span asp-validation-for="PublishDate" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Files" class="control-label"></label>
    <input asp-for="Files" id="post-files" class="form-control" accept="audio/*, image/*" />
    <span asp-validation-for="Files" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Tags" class="control-label"></label>
    <select asp-for="Tags" class="form-control tag-selector-post" multiple>
        @foreach (string tag in Model.Tags)
        {
            <option id="@tag" value="@tag" selected>@tag</option>
        }
    </select>
    <span asp-validation-for="Tags" class="text-danger"></span>
</div>